### ISSUE TITLE
Chinese Lang Support

### ISSUE THREAD

**Issue by 892768447** [FriendsOfFlarum/best-answer#1]
Nice project, and here I have prepared some Chinese translation files,
Hope to get support

locale
|-----cn.yml
|-----zh.yml
|-----zh-hans.yml

[locale.zip](https://github.com/FriendsOfFlarum/best-answer/files/3961608/locale.zip)

**Comment by datitisev** [comment]
Thanks for the translations. Sadly, we won't be adding them as we've decided to only maintain English locale and leave other languages to language packs (you can read more about why [here](https://discuss.flarum.org/d/19971-extensions-translation-in-their-own-repository-or-in-language-pack)).

Feel free to PR to a Chinese language pack with these translations, but I'll be closing this issue.

Thank you!
