### ISSUE TITLE
TypeError: this.discussion.bestAnswerUser is not a function

### ISSUE THREAD

**Issue by DavideIadeluca** [FriendsOfFlarum/best-answer#102]
## Bug Report

**Current Behavior**
A clear and concise description of the behavior.

**Steps to Reproduce**
1. Go to PostsUserPage

**Expected Behavior**

**Screenshots**

**Environment**
- Flarum version: x.y.z
- Extension version: x.y.z
- Website URL: http://example.com
- Webserver: [e.g. apache, nginx]
- Hosting environment: [e.g. shared, vps]
- PHP version: x.y.z
- Browser: [e.g. chrome 67, safari 11]

```
Output of "php flarum info", run this in terminal in your Flarum directory.
```

**Possible solution(s)**

**Additional Context**

**Comment by imorland** [comment]
Possibly fixed in https://github.com/FriendsOfFlarum/best-answer/commit/dfb6a8a2a9c4b73e994ca2c2aad944e30cf04d98

**Comment by DavideIadeluca** [comment]
Will double check momentarily

**Comment by imorland** [comment]
Not fully

![image](https://github.com/user-attachments/assets/2d4e89f0-9093-4bb8-8f73-136666a06385)
