### ISSUE TITLE
imcompatible with the-turk/flarum-mathren

### ISSUE THREAD

**Issue by ustcwxz** [FriendsOfFlarum/best-answer#20]
imcompatible with [the-turk/flarum-mathren](https://github.com/the-turk/flarum-mathren)

**Comment by datitisev** [comment]
How is it incompatible?

**Comment by ustcwxz** [comment]
the mathren library is help to display math formula.

**Comment by imorland** [comment]
As `the-turk/flarum-mathren` appears to be abandoned, I'll close this issue now.
