### ISSUE TITLE
[BUG] Selected Post Does Not Exist in This Discussion

### ISSUE THREAD

**Issue by andrewdmaclean** [FriendsOfFlarum/best-answer#26]
### Description of Issue
Facing the "Selected Post Does Not Exist" bug on a recent update to Beta 15, but only in PROD, while localhost has no issues.

### Attempted Solutions 
- If I manually change the DB entries in PROD, the forum reflect the "Best Answer" appropriately, so I am thinking it may have something to do with the POST request not being accepted by the DB?
- Even if I disable all extensions the error still occurs.

### Thoughts
The only thing I have been able to find in terms of notable differences is that PROD is running MariaDB while localhost is running a MySQL Server.

### Similar Issues
From the description on Discuss, it is the same issue as outined here https://discuss.flarum.org/d/24960-best-answer-issue/10 

### Screenshots of the Error
![image](https://user-images.githubusercontent.com/26526271/102918960-cba13b80-443c-11eb-90ef-fab6a2f97e74.png)
![image](https://user-images.githubusercontent.com/26526271/102919021-e7a4dd00-443c-11eb-97d6-5aac6a4b9296.png)
![image](https://user-images.githubusercontent.com/26526271/102919087-10c56d80-443d-11eb-91fa-89e7e99ac3c6.png)

**Comment by imorland** [comment]
This has popped up every now and again for a while now. Should have an hour or two to look at this soon

**Comment by EvilExecutor** [comment]
@andrewdmaclean Thanks for reporting this issue & helping out to find a fix. It's been fixed on FriendsOfFlarum Best Answer
 v0.3.2. If you are interested to know how this was fixed >  https://github.com/FriendsOfFlarum/best-answer/commit/915515b145c93627c819745cd2bde8d5c3f0e885

If you still experience the issue feel free to open.
