### ISSUE TITLE
[deleted] user problem

### ISSUE THREAD

**Issue by tolgaaaltas** [FriendsOfFlarum/best-answer#31]
Hello dear FoF team,
I don't know why this is happening but sometimes when I visit my profile, some posts seems to have been selected as "best answer" by a deleted user. If i'm going to actual post, everything works fine. I checked my browser's console but there is no error.

Example:
![image](https://user-images.githubusercontent.com/10291048/106441942-bda6f780-648b-11eb-91e9-fd3daf8e15ea.png)
This post actually selected best answer by lalare (you can see the user as replier). He is not a deleted user, I spotted this error on the FlarumTR site.

**Comment by datitisev** [comment]
Could this be related to https://github.com/flarum/core/issues/1844, https://github.com/flarum/core/issues/2404? Or a different issue altogether? 🤔

**Comment by imorland** [comment]
Related to #34 - relationships are not correctly loaded on the `UserPage`
