### ISSUE TITLE
Restrict Q&A feature to specific tags

### ISSUE THREAD

**Issue by eddiewebb** [FriendsOfFlarum/best-answer#35]
I I'd like to limit the "best answer" button to a particular tag.  So to focus an area for Q&A vs general discussion.

bonus, not key: I think it would then be cool to perhaps add a badge or otherwise emboss that tag and post avatars to indicate a Q&A format.

**Comment by imorland** [comment]
This can already be done by setting the extension global permissions to admin only, then creating a custom permissioned tag. Something like this:

![image](https://user-images.githubusercontent.com/16573496/128420161-4ee81685-6d2e-44ea-b375-705f7b8c23c6.png)

**Comment by eddiewebb** [comment]
Sorry yes, that makes perfect sense. Thank you!
