### ISSUE TITLE
Little CSS Fix for mobile

### ISSUE THREAD

**Issue by justoverclockl** [FriendsOfFlarum/best-answer#39]
very little fix on mobile, here the screenshot

https://ibb.co/fQYybdt

**Comment by imorland** [comment]
This appears to be fine in the latest code, to be released shortly. I'll close this issue now, but feel free to let us know if the problem persists after the `1.0.0` version has been released

![image](https://user-images.githubusercontent.com/16573496/119260984-20ec9f00-bbcd-11eb-8dd3-d2adb42fdd78.png)
