### ISSUE TITLE
Css issues

### ISSUE THREAD

**Issue by justoverclockl** [FriendsOfFlarum/best-answer#43]
Css must be fixed here it goes off div

Screenshot:

![Immagine 2021-05-26 173449](https://user-images.githubusercontent.com/79002016/119688967-c1022c80-be48-11eb-85b0-44a1e09d3ae1.png)

**Comment by imorland** [comment]
Which version of the extension are you using?

**Comment by justoverclockl** [comment]
my dev environment are on beta 16, installed with :*

**Comment by justoverclockl** [comment]
> Which version of the extension are you using?
> 
> This is the output in `1.0`
> ![image](https://user-images.githubusercontent.com/16573496/119689598-e4c17480-be40-11eb-828f-2ed565b6cf43.png)

oh so its fixed only for 1.0, its ok is just to notice u of this ;)

**Comment by imorland** [comment]
Although it's entirely possible the `read more` extension is not playing nicely 🤔

**Comment by justoverclockl** [comment]
> Although it's entirely possible the `read more` extension is not playing nicely 🤔

it happens even without this extension

**Comment by imorland** [comment]
Ah ok. Yeah, so this appears to not be an issue in the latest version, so I'll close this issue now. Feel free to re-open once you've upgraded to `1.0` if you still have any issues with this
