### ISSUE TITLE
Add "Solved" tag if best answer is selected

### ISSUE THREAD

**Issue by Hari-Bonda** [FriendsOfFlarum/best-answer#46]
## Feature Request

Automatically Add the "Solved" tag to the discussion if the best answer is selected

**Comment by Hari-Bonda** [comment]
i think we can achieve this using auto moderator

**Comment by ramesh-dada** [comment]
@Hari-Bonda No we can't achieve this by using auto moderator it defines whether users qualify for a criterion not the discussion qualify for criterion and there is no such option to add tag.

**Comment by Hari-Bonda** [comment]
oh, it would be nice if the extension adds a particular tag if the best answer is selected.

**Comment by katosdev** [comment]
Could probably do this through an extender, and have a setting in the Admin panel for the tag to use. Pseudo code would look like this:

If {
discussion === ‘solved’ {
add tag: $solved_tag
}
return;
}

**Comment by Hari-Bonda** [comment]
> Could probably do this through an extender, and have a setting in the Admin panel for the tag to use. Pseudo code would look like this:
> 
> If {
> discussion === ‘solved’ {
> add tag: $solved_tag
> }
> return;
> }

how can we add event activity? like the solved tag was added by the System or admin
