### ISSUE TITLE
Option to Filter Answered or Unanswered posts

### ISSUE THREAD

**Issue by ramesh-dada** [FriendsOfFlarum/best-answer#48]
Hello I have a feature idea from Dicourse I seen in discourse that we can easily filter topics that are solved or unsolved and that text should be translatable 
![image](https://user-images.githubusercontent.com/75124237/127437113-394c6d8e-cf2c-4b83-a4cb-ee8c840582d3.png)

**Comment by imorland** [comment]
This is already _partially_ implemented but not obvious.

The gambit `is:solved` will show all solved discussions, and `-is:solved` will show all unsolved discussions. There's currently no UI for this toggle, and the unsolved results will not take into account any discussions in tags where best answers are not permitted.

**Comment by ramesh-dada** [comment]
@imorland Thank You So much for adding this feature 🙏🙏
