### ISSUE TITLE
migration fails if `fof-best-answer.remind_tag_ids` is empty

### ISSUE THREAD

**Issue by frankli0324** [FriendsOfFlarum/best-answer#50]
## Bug Report

**Steps to Reproduce**

1. Set `remind_tag_ids` to an empty string in admin panel
2. ./flarum migrate

**Expected Behavior**

Migration *happens*

**Screenshots**

![image](https://user-images.githubusercontent.com/20221896/130177882-02f0b163-8355-416a-add1-c7a615070f73.png)

**Possible solution(s)**

add some null check to the migration

**Comment by imorland** [comment]
Thanks for the report. This should now be resolved in release `1.1.1`
