### ISSUE TITLE
Select Best Answer button not showing up

### ISSUE THREAD

**Issue by Nzii3** [FriendsOfFlarum/best-answer#73]
## Bug Report

**Current Behavior**
I have the **FoF Best Answer** extension enabled and have it enabled on all tags. But it doesn’t seem to show up in the drop-down menu on a post/reply.

![F3DDD20A-F4EC-45F7-A691-B3360F90A7EA](https://user-images.githubusercontent.com/106406461/205201185-97ea643b-64e3-4b83-85b1-698683a3232f.jpeg)

**Steps to Reproduce**
1. Go to a post/discussion
2. Click on '**…**'
3. See there isn’t a **Select Best Answer** button

**Expected Behavior**
The best answer button should be in the drop down and shouldn’t be hidden.

**Screenshots**
![82F21A00-69DB-49B1-A2CD-FFF3E6EB201E](https://user-images.githubusercontent.com/106406461/205201388-8d3d1e0f-4e57-436a-ad2b-28496c64c408.jpeg)
![411053AB-4FDE-46DA-8C49-BAEF332E7E2C](https://user-images.githubusercontent.com/106406461/205201558-fd1f7724-7299-4694-acbe-2e16756bb34a.jpeg)

**Environment**
- Flarum version: 1.6.2
- Extension version: 1.2.4
- Website URL: https://forum.servermanagerbot.ml
- Webserver: *idk*
- Hosting environment: freeflarum website
- PHP version: 8.1.2
- Browser: Chrome and Safari (doesn’t work on both)

```
Output of "php flarum info", run this in terminal in your Flarum directory. - I’m not self hosting
```

**Possible solution(s)**

None

**Additional Context**

**Comment by Nzii3** [comment]
Nvm got this fixed.

**Comment by LoneDev6** [comment]
> Nvm got this fixed.

@Nzii3 
How? I too have this issue.
Thanks

**Comment by Nzii3** [comment]
@LoneDev6 It kind of fixed itself for me, idk how. Try resetting all of the settings and permissions for the categories.

**Comment by LoneDev6** [comment]
I'd like to get a proper answer from the developer sincerely, this is not helpful at all.
Thanks anyway.
@imorland @dsevillamartin any idea?

**Comment by LoneDev6** [comment]
Any news on this? @imorland @dsevillamartin

**Comment by LoneDev6** [comment]
Fixed by editing the source.
https://github.com/LoneDev6/fof-best-answer/commit/ab4b3882a75d15c4e1ff4b7c9adb1a2e290d8893
