### ISSUE TITLE
Allow Secondary Tags in Enabled Tags

### ISSUE THREAD

**Issue by milindsingh** [FriendsOfFlarum/best-answer#92]
## Feature Request

**Is your feature request related to a problem? Please describe.**

Allow Secondary Tags in Enabled Tags

**Describe the solution you'd like**

Allow Secondary Tags in Enabled Tags

**Comment by imorland** [comment]
Included in `1.4.3`

**Comment by milindsingh** [comment]
Thank you so much for adding this.
